/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kellyfj' at '9/15/15 12:16 PM' with Gradle 2.7
 *
 * @author kellyfj, @date 9/15/15 12:16 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
